### ISSUE TITLE
Error when using connection string with Authentication property.

### ISSUE THREAD

**Issue by statler** [sjh37/efreversepoco#828]
Error when using connection string with Authentication property. This property is used for supporting SSO connections to Azure.

E.g. Data Source=[azuresqldb].database.windows.net;Initial Catalog=[azuredbname];Encrypt=False;Authentication=ActiveDirectoryInteractive;TrustServerCertificate=true

// ------------------------------------------------------------------------------------------------
// WARNING: Failed to load provider "System.Data.SqlClient" - Invalid value for key 'authentication'.
// Allowed providers:
//    "System.Data.Odbc"
//    "System.Data.OleDb"
//    "System.Data.OracleClient"
//    "System.Data.SqlClient"
//    "System.Data.SqlServerCe.4.0"
//    "Microsoft.SqlServerCe.Client.4.0"
//    "Microsoft.Data.SqlClient"

/*   at System.Data.Common.DbConnectionStringBuilderUtil.ConvertToAuthenticationType(String keyword, Object value)
   at System.Data.SqlClient.SqlConnectionString.ConvertValueToAuthenticationType()
   at System.Data.SqlClient.SqlConnectionString..ctor(String connectionString)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnectionOptions(String connectionString, DbConnectionOptions previous)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPoolGroup(DbConnectionPoolKey key, DbConnectionPoolGroupOptions poolOptions, DbConnectionOptions& userConnectionOptions)
   at System.Data.SqlClient.SqlConnection.ConnectionString_Set(DbConnectionPoolKey key)
   at System.Data.SqlClient.SqlConnection.set_ConnectionString(String value)
   at Microsoft.VisualStudio.TextTemplating5BF9448DEF9426DF90CC587C9AC1EF01603B2338EE55147D4C0EE042D5B0CD70C71E4B2232D6B533FBEBFCF161051401ECFBA8A90270522134325DF57D3F8575.GeneratedTextTransformation.DatabaseReader.Init() in C:\Users\dennisg\source\repos\CPDBManager\CPDBManager\EF.Reverse.POCO.v3.ttinclude:line 12530
   at Microsoft.VisualStudio.TextTemplating5BF9448DEF9426DF90CC587C9AC1EF01603B2338EE55147D4C0EE042D5B0CD70C71E4B2232D6B533FBEBFCF161051401ECFBA8A90270522134325DF57D3F8575.GeneratedTextTransformation.SqlServerDatabaseReader.Init() in C:\Users\dennisg\source\repos\CPDBManager\CPDBManager\EF.Reverse.POCO.v3.ttinclude:line 16421
   at Microsoft.VisualStudio.TextTemplating5BF9448DEF9426DF90CC587C9AC1EF01603B2338EE55147D4C0EE042D5B0CD70C71E4B2232D6B533FBEBFCF161051401ECFBA8A90270522134325DF57D3F8575.GeneratedTextTransformation.Generator.Init(DatabaseReader databaseReader, String singleDbContextSubNamespace) in C:\Users\dennisg\source\repos\CPDBManager\CPDBManager\EF.Reverse.POCO.v3.ttinclude:line 4278
   at Microsoft.VisualStudio.TextTemplating5BF9448DEF9426DF90CC587C9AC1EF01603B2338EE55147D4C0EE042D5B0CD70C71E4B2232D6B533FBEBFCF161051401ECFBA8A90270522134325DF57D3F8575.GeneratedTextTransformation.GeneratorFactory.Create(FileManagementService fileManagementService, Type fileManagerType, String singleDbContextSubNamespace) in C:\Users\dennisg\source\repos\CPDBManager\CPDBManager\EF.Reverse.POCO.v3.ttinclude:line 6513*/
// ------------------------------------------------------------------------------------------------

**Comment by sjh37** [comment]
Duplicate of #807
